apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      index index.html;
      location / {
          proxy_pass  http://frontend:5000/;
          return 200 "Small Mistake UPS, DELETE ME\n";
      }
    }